// <auto-generated />
using AssignmentWebAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssignmentWebAPI.Migrations
{
    [DbContext(typeof(FamiliesDbContext))]
    [Migration("20211119135810_JobProblemForeignKey5")]
    partial class JobProblemForeignKey5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("AssignmentWebAPI.Model.LoginUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AssignmentWebAPI.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EyeColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("AssignmentWebAPI.Model.Adult", b =>
                {
                    b.HasBaseType("AssignmentWebAPI.Model.Person");

                    b.HasDiscriminator().HasValue("Adult");
                });

            modelBuilder.Entity("AssignmentWebAPI.Model.Adult", b =>
                {
                    b.OwnsOne("AssignmentWebAPI.Model.Job", "JobTitle", b1 =>
                        {
                            b1.Property<int>("AdultId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("JobTitle")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Salary")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AdultId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("AdultId");
                        });

                    b.Navigation("JobTitle");
                });
#pragma warning restore 612, 618
        }
    }
}
